set-bed-spawn: true
share-of-players: 0.5
messages:
  set-spawn: "&7&lBed spawn set"
  no-permission: "&4No permission"
  good-morning: "&6Good morning! The night was skipped"
  went-to-bed: "&f%player%&7 went to bed (%sleeping%% sleeping)"
  left-bed: "&f%player%&7 left the bed (%sleeping%% sleeping)"
  commands:
    default: "&7&lYou're running Morpheus %version%\n&7Commands:\n&7 â€” &f/morpheus toggle&7: toggle the plugin"
    enabled: "&7&lSleep voting is now activated"
    disabled: "&7&lSleep voting is now inactivated"